NAME= 		main
TEXSRCS= 	$(wildcard *.tex) \
			doctools/latex/magazine_template.tex \
			doctools/latex/mycommands.tex
XDVI_FLAGS= -paper letter -interpreter /usr/bin/X11/gs
DVIPS_FLAGS= -t letter
XFIGSRCS=	figs/usart_pinout.fig
include /usr/share/latex-mk/latex.gmk

